### ISSUE TITLE
希望获得部分知乎热榜及其热度数据用于疫情可视化

### ISSUE THREAD

**Issue by pearmini** [mjrao/hotso#1]
先生您好，我是山东大学 VisLab 实验室的学生，近期我们在做新冠状病毒舆论和新闻方面的可视化工作：想了解疫情过程中，人们在讨论什么。系统其中一部分就是可视化知乎热榜的热度变化，但是我们这里只有只有2月27日之后的数据，希望能从您这里获得从 1月20日 到 2月28日 知乎热榜及其热度的数据。我们在系统中会注明这部分数据来自您这里，如果您能给我们分享你的数据，我们感激不尽！这里是现在的系统 ：https://pearmini.gitee.io/ncovis-2020/#/。

**Comment by ai0376** [comment]
好的，我整理个接口，发布出来



---原始邮件---
发件人: "pearmini"<notifications@github.com&gt;
发送时间: 2020年4月5日(周日) 晚上10:57
收件人: "mjrao/hotso"<hotso@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [mjrao/hotso] 希望获得部分知乎热榜及其热度数据用于疫情可视化 (#1)




 
先生您好，我是山东大学 VisLab 实验室的学生，近期我们在做新冠状病毒舆论和新闻方面的可视化工作：想了解疫情过程中，人们在讨论什么。系统其中一部分就是可视化知乎热榜的热度变化，但是我们这里只有只有2月27日之后的数据，希望能从您这里获得从 1月20日 到 2月28日 知乎热榜及其热度的数据。我们在系统中会注明这部分数据来自您这里，如果您能给我们分享你的数据，我们感激不尽！这里是现在的系统 ：https://pearmini.gitee.io/ncovis-2020/#/。

**Comment by pearmini** [comment]
万分感谢！

**Comment by ai0376** [comment]
> 万分感谢！

查询接口已发 https://github.com/mjrao/hotso/blob/master/README.md#%E6%95%B0%E6%8D%AE%E6%A0%B7%E4%BE%8B

**Comment by pearmini** [comment]
> > 万分感谢！
> 
> 查询接口已发 https://github.com/mjrao/hotso/blob/master/README.md#%E6%95%B0%E6%8D%AE%E6%A0%B7%E4%BE%8B

嗯嗯，收到！
